arb-dir: lib/l10n # .arb define path of language files
template-arb-file: app_tr.arb # default language
synthetic-package: false
output-localization-file: app_localizations.dart # auto created file
output-dir: lib/gen